apiVersion: v1
kind: Service
metadata:
  name: {{ include "team1-chart.fullname" . }}
  labels:
    {{- include "team1-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: http
  selector:
    {{- include "team1-chart.selectorLabels" . | nindent 4 }}