---
# alertmanager:
#   ingress:
#     enabled: true

prometheus:
  ingress:
    enabled: true
    paths: ["/"]
    hosts:
      - prometheus.${external_dns_ingress_dns}
 
# grafana:
#   ingress:
#     enabled: true