---
alertmanager:
  ingress:
    enabled: true
    paths: ["/"]
    hosts:
      - alertmanager.${external_dns_ingress_dns}

prometheus:
  ingress:
    enabled: true
    paths: ["/"]
    hosts:
      - prometheus.${external_dns_ingress_dns}
 
grafana:
  ingress:
    enabled: true
    path: "/"
    hosts:
      - grafana.${external_dns_ingress_dns}