name: Terraform validation

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Validate
      run: |
        terraform init
        terraform fmt
        terraform validate
        terraform plan
