name: Terraform validation


on:
  push:
    branches:
     - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.clientId }}
      ARM_CLIENT_SECRET: ${{ secrets.clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.subscriptionId }}
      ARM_TENANT_ID: ${{ secrets.tenantId }}
      ARM_ACCESS_KEY: ${{ secrets.accessKey }}
      working-directory: ./Oppgave1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Terraform fmt check'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.20
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: ${{env.working-directory}}
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # run: terraform fmt -check=true -write=false -diff -recursive
    - name: 'Terraform init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.20
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: ${{env.working-directory}}
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # run: terraform init
      # working-directory: ${{env.working-directory}}
    - name: 'Terraform validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.20
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: ${{env.working-directory}}
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # run: terraform validate
      # working-directory: ${{env.working-directory}}
    - name: 'Terraform plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.20
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: ${{env.working-directory}}
        args: |-
          -out=tfplan
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # run: terraform plan
      # working-directory: ${{env.working-directory}}


    - name: Upload plan
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v1
      with:
        name: tfplan
        path: ${{env.working-directory}}/tfplan

    - name: 'Terraform apply'
      if: github.event_name == 'push'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.20
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: ${{env.working-directory}}
        args: |-
          tfplan
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # if: github.event_name == 'push'
      # run: terraform apply -auto-approve
      # working-directory: ${{env.working-directory}}