name: Terraform validation

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Validate
      env:
        ARM_CLIENT_ID: ${{ secrets.clientId }}
        ARM_CLIENT_SECRET: ${{ secrets.clientSecret }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.subscriptionId }}
        ARM_TENANT_ID: ${{ secrets.tenantId }}
        ARM_ACCESS_KEY: ${{ secrets.accessKey }}
      working-directory: ./Oppgave1
      run: |
        terraform fmt -check=true -write=false -diff -recursive
        terraform init
        terraform validate
        terraform plan -detailed-exitcode
      # run: terraform fmt -check=true -write=false -diff -recursive
      # run: terraform init
      # run: terraform validate
      # run: terraform plan -detailed-exitcode